usage: test.py [-h] [--experiment EXPERIMENT] [--model MODEL]
               [--root_dir ROOT_DIR] [--num_class NUM_CLASS]
               [--tile_dict_path TILE_DICT_PATH] [--val VAL]
test.py: error: unrecognized arguments: --root_dir/gpfs/data/abl/deepomics/tsirigoslab/histopathology/Tiles/LungTilesSorted/
